// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugeftirrsncpdncbwkkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZWZ0aXJyc25jcGRuY2J3a2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDE0OTgsImV4cCI6MjA2MzQxNzQ5OH0.G2S0Yu7lHC2zezFYTX4p2OXuQSX7Fw5h7RJrSJPzTpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);